<?php

########################################################################
# Extension Manager/Repository config file for ext: "simteaser"
#
# Auto generated by Extension Builder 2012-05-28
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple image teaser',
	'description' => 'Simple image teaser showing a view linked images',
	'category' => 'plugin',
	'author' => 'Roman Buechler',
	'author_email' => 'rb@synac.com',
	'author_company' => 'Synac Technology, S.L.',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			't3jquery' => '0.0',
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>